### ISSUE TITLE
New name? and publishing

### ISSUE THREAD

**Issue by jcs090218** [junyi-hou/tree-sitter-fold#3]
Hi,

I have a fork of this repository [here](https://github.com/jcs090218/tree-sitter-fold). I was planning to contribute back to upstream, but then I realized I have gone too far and it would be difficult to review and merge.  Here are some of my concerns. Do you have plan to publish this to ELPA/MELPA? If no, can I publish my own fork with the name `tree-sitter-fold`? Or should I rename it to something else?

Since you are the original author, it would be great to hear what you think! And I appreciate this amazing project! 😁 👍

**Comment by junyi-hou** [comment]
Hi @jcs090218, thank you for your interests on working on the project (and sorry for the late reply!). Here is what I think:
1. I am planning on keep working on `tree-sitter-fold`
2. That being said, I have no plan to publish it on ELPA/MELPA

so here is what I propose: feel free to publish your work, but maybe use a new name to avoid confusion.

Let me know what you think!

**Comment by jcs090218** [comment]
Got it! I will rename it to something else! :)

Thanks for replying to my concerns!

**Comment by milkypostman** [comment]
@junyi-hou is it at all possible to merge in changes instead of forking? I know jcs090218 said "it's gone too far" but "it would be difficult to review and merge" seems like a call for @junyi-hou.

In general it’s better for the community to have a single package and improve that unless there are major architectural differences between the packages. 

On a separate note, MELPA is designed to be author independent. While we do try to respect authors wishes about publishing packages, since we don’t require authors to do anything specific and because the package code is open source, there is no reason your package won’t end up on MELPA at some point. MELPA is simply a different mechanism to install a package instead of `git clone`
